# -*- coding: utf-8 -*-
"""PROJETOPYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XBuE6UkSiOaqyZVq_RF6z2IzF6JYGht1
"""

from google.colab import drive

drive.mount('/content/drive')

import os

!ls 'drive/MyDrive/PROJETOPYTHON1'

os.chdir('drive/MyDrive/PROJETOPYTHON1')

!ls

import pandas as pd

df = pd.read_csv("dadosvoos_2007.csv")

df

grupo = df.groupby(['Origin'])

grupo.groups.keys()

df['Origin'].unique()

grp = grupo.get_group('SMF')

grp

grp = grupo.get_group('BET')

grp

grupo = df.groupby(['Origin', 'Dest']).count()

grupo

grp.count()

grp = df.groupby(['Origin','Dest'])
grp2 = df.groupby(['Dest' , 'Origin'])

list(grp.groups.keys())[5]

list(grp2.groups.keys())[5]

grp2.count()

import numpy as nm

list_grp = list(grp.groups.keys())
len(list_grp)

list_grp1 = list(grp2.groups.keys())
len(list_grp1)

list_grp1